### ISSUE TITLE
Jumlah Total SKS Terambil Masih Bisa Lebih Dari 25

### ISSUE THREAD

**Issue by banghajidotcom** [osi-stmikplk/siakad#13]
Silahkan pilih salah satu MK pada saat isi FRS dengan jumlah SKS adalah lebih dari 25. Pasti masih bisa terpilih :D ... 

Pull Request untuk fixing bug menyusul.

**Comment by yfktn** [comment]
confirmed ... nunggu pull request kalau begitu :D

**Comment by yfktn** [comment]
thanks fix selesai ...
