### ISSUE TITLE
Bug FRS

### ISSUE THREAD

**Issue by abdidnugraha** [osi-stmikplk/siakad#15]
Error terjadi ketika mahasiswa akan melakukan penambahan atau pengurangan mata kuliah yang akan di tempuh di FRS.
![error](https://cloud.githubusercontent.com/assets/19319834/16294641/e5c9d950-394b-11e6-9a2e-a64eac6fa7d3.jpg)

**Comment by osi-stmikplk** [comment]
Saya tidak dapat melakukan reproduksi terhadap bug ini :(

Coba check struktur table rencana_studi dan rincian_studi. Serta pastikan sudah melakukan proses migrate terbaru. Karena kalau melihat dari error yang muncul ini dikarenakan gagal mendapatkan nilai semester dari table rencana_studi seperti yang terlihat di 

https://github.com/osi-stmikplk/siakad/blob/dev/app/Factories/IsiFRSFactory.php#L84

Mohon info lebih lanjut ...

**Comment by banghajidotcom** [comment]
ganti nama field di tabel rencana_studi dari SMT menjadi semester bang...
maaf itu kemaren sayah masih pakai hasil konversih dgn nama field SMT :v:

**Comment by osi-stmikplk** [comment]
haha berarti fix dong ini ya karena masalah migrasi data :octopus:
