### ISSUE TITLE
Script Migrasi Persiapan User Id Mahasiswa

### ISSUE THREAD

**Issue by osi-stmikplk** [osi-stmikplk/siakad#17]
Karena banyaknya mahasiswa maka sangat tidak baik apabila harus di entry satu per satu, maka akan lebih baik apabila proses generate untuk userid mahasiswa dilakukan dengan script.

Salah satu usulan adalah untuk meminta masing-masing angkatan menyediakan file csv dengan format:

nomor-induk-mahasiswa | email-mahasiswa

Kemudian script akan melakukan generate berupa entry user dan generate password default yang akan dikirimkan kepada mahasiswa melalui email yang diberikan.

**Comment by banghajidotcom** [comment]
setuju, yang ngerjakan @abdidnugraha :)

**Comment by osi-stmikplk** [comment]
kalau begitu perlu diskusi lebih lanjut di sini. Bagaimana dengan si @abdidnugraha ?

**Comment by abdidnugraha** [comment]
_melambaikan tangan ke kamera_ #tidakkuat

**Comment by osi-stmikplk** [comment]
Dibuat default saja, username adalah NIM dan password adalah tanggal lahir.

76af5b11d0d5732ebe96dd358ec6fe826c8a8e25
