### ISSUE TITLE
Issue Fitur Filter KHS & Form Data Diri

### ISSUE THREAD

**Issue by jabbarbie** [osi-stmikplk/siakad#20]
untuk mutu / nilai di transkrip yg mendapatkan nilai e kalau bisa tidak di tampilkan pak.. soalnya untuk  total sks nya jadi makin banyak.. atau kalau mungkin di buatkan filter untuk user ingin menampilkan nilai e / tidak. atau bisa juga di beri keterangan lagi untuk total khsnya yg lulus & tidak.

Form edit data diri, fungsi maxlength dibagian nomor yg bisa dihubungi tidak berfungsi, dan juga setelah submit form ada alert merah yg masih ada walaupun kondisi sudah benar.. tapi overall, keren pak (y)(y)

**Comment by osi-stmikplk** [comment]
> untuk mutu / nilai di transkrip yg mendapatkan nilai e kalau bisa tidak di tampilkan pak.. soalnya untuk total sks nya jadi makin banyak.. atau kalau mungkin di buatkan filter untuk user ingin menampilkan nilai e / tidak. atau bisa juga di beri keterangan lagi untuk total khsnya yg lulus & tidak.

Untuk hal ini setahu saya bukankah dalam transkrip nilai itu ditampilkan yang sudah diambil? Kecuali kalau kemudian MK tersebut dibatalkan. Butuh konfirmasi lanjut ini untuk aturan di kampus seperti apa.

> Form edit data diri, fungsi maxlength dibagian nomor yg bisa dihubungi tidak berfungsi, dan juga setelah submit form ada alert merah yg masih ada walaupun kondisi sudah benar..

Apa bisa dijelaskan lebih lanjut untuk issue yang ini @jabbarbie ? Karena memang maxlength adalah 50 karakter.

**Comment by qulez** [comment]
betul pak yan... setiap matakuliah yang pernah ditempuh menyesuaikan kurikulum sehingga wajib tampil di transkrip..kecuali mata kuliah pilihan yang diambil berlebih..(khusus Kurikulum TI 2013).

**Comment by osi-stmikplk** [comment]
> betul pak yan... setiap matakuliah yang pernah ditempuh menyesuaikan kurikulum sehingga wajib tampil di transkrip..kecuali mata kuliah pilihan yang diambil berlebih..(khusus Kurikulum TI 2013).

Bagaimana mekanismenya ini seperti pertanyaan @jabbarbie , berkaitan dengan filter yang ditampilkan apabila MK ini tidak ditampilkan. Kalau seingat saya, untuk menghilangkan dari catatan maka harus dibatalkan melalui AKMA.

**Comment by abdidnugraha** [comment]
> Bagaimana mekanismenya ini seperti pertanyaan @jabbarbie , berkaitan dengan filter yang ditampilkan apabila MK ini tidak ditampilkan. Kalau seingat saya, untuk menghilangkan dari catatan maka harus dibatalkan melalui AKMA.

@osi-stmikplk Kalau mengikuti mekanisme pencetakan transkrip yang ada sekarang, untuk matakuliah dengan nilai E tidak ditampilkan di transkrip pak, yang ditampilkan untuk nilai terendah adalah D.

**Comment by qulez** [comment]
dengan kata lain Mata kuliah yang pernah diambil kalau nilainya E maka dianggap tidak pernah menempuh atau nilai belum masuk dari dosen juga ya pak abdi?

**Comment by abdidnugraha** [comment]
> dengan kata lain Mata kuliah yang pernah diambil kalau nilainya E maka dianggap tidak pernah menempuh atau nilai belum masuk dari dosen juga ya pak abdi?

Iya pak @qulez karena nilai yang belum masuk dari dosen dianggap E.

**Comment by qulez** [comment]
Nah clear pak yan...berarti di Transkrip Nilai Khusus Nilai E tidak perlu ditampilkan.. :)

**Comment by osi-stmikplk** [comment]
Oke sip kalau begitu. Akan ditindaklanjuti.
