### ISSUE TITLE
ErrorException di halaman persetujuan FRS

### ISSUE THREAD

**Issue by jabbarbie** [osi-stmikplk/siakad#22]
![1_seeder_tahun](https://cloud.githubusercontent.com/assets/4547730/17254607/a87c9672-55df-11e6-924f-e4bfd42e8ba8.png)
1. Setelah login menggunakan user admin
2. lalu masuk ke menu master - persetujuan FRS
3. dan muncul error seperti pada gambar diatas. 

indikasi errornya sepertinya fungsi getTAAktif() tidak menemukan data pd table referensi_akademik. soalnya untuk versi dev. tidak ada seeder untuk table tersebut... tapi pada halaman status spp dan kelas & dosen tidak error padahal table tsb jg kosong

**Comment by osi-stmikplk** [comment]
@jabbarbie  kok di close? Sudah dapat penyebabnya? Masalahnya saya sudah nyoba belum dapat error yang sama muncul ...

**Comment by jabbarbie** [comment]
Sudah pak, waktu datanya saya isi manual di table referensi_akademik, dan tidak muncul error lagi tapi pilih tahun angkatan akademi yang seharusnya dropdown menjadi textbox biasa.

**Comment by osi-stmikplk** [comment]
Ini karena seeder yang kurang lengkap pada waktu membuat aplikasi dari awal, jadi semestinya ditambahkan juga seeder untuk isian pada ReferensiAkademik.

@jabbarbie ini **relatif mudah dibuat**, apa mau ikut ngoding dan mengirimkan pull request ke sini ;) ?

**Comment by jabbarbie** [comment]
wah, kalo itu mau banget saya pak.. tapi untuk laravel sendiri, saya masih **baru kenalan** kemarin , jadi ya sementara ini cuma bisa jadi tester saja. :)

**Comment by osi-stmikplk** [comment]
Itu mudah sekali kok @jabbarbie, untuk bikin seeds tersebut.
- https://github.com/osi-stmikplk/siakad/tree/dev/database/seeds
- http://digitalmapia.com/cara-melakukan-seeding-pada-laravel/

Silahkan kita berdiskusi kalau ada kesukaran. Bisa juga dipanggilkan rekan-rekan mahasiswa yang lain.

:gun: :racehorse:

**Comment by banghajidotcom** [comment]
seret temen2nya semua, kalo ga mau, ditembak :sunglasses:

**Comment by jabbarbie** [comment]
Ok. Siap pak,. Untuk penggunaaan seeds, masih mudah dipahami.. apalagi untuk Fitur fake seeder, itu fitur Keren banget.. 

Kalau rekan dengan hobi yang sama, saya tak punya pak.. jadi tidak ada yang perlu di tembak :)

**Comment by banghajidotcom** [comment]
yaudah kamu nembak siapa aja gitu yg mau ditembak  :sunglasses:

**Comment by osi-stmikplk** [comment]
yang nyuruh nembak gak ketembak-tembak :panda_face: Kami tunggu pull request nya

**Comment by jabbarbie** [comment]
Masalahnya belum ada yang rela pak buat saya tembak ;) 

Terima kasih pak untuk responnya, kasus selesai 😎

**Comment by osi-stmikplk** [comment]
Wei kok kasus selesai? Mana nih pull request nya? 
- http://stackoverflow.com/questions/14680711/how-to-do-a-github-pull-request

**Comment by banghajidotcom** [comment]
ini issue sdh berapa kali di close jadi open lagi  :laughing:

**Comment by jabbarbie** [comment]
Sudah 2x kali ini pak 😭

Buku pedoman saya sudah sampai.. tapi sayanya lgi diluar kota. Jadi untuk pull request nya di tunggu saja pak.

**Comment by osi-stmikplk** [comment]
haha oke kami tunggu deh kalo gitu. Nih issue jangan do close sampai resolve dulu > biar kualitas tinggi :laughing: :rocket: :roller_coaster:
