### ISSUE TITLE
Ubah Render Tampilan Tahun Ajaran Admin -> SPP

### ISSUE THREAD

**Issue by osi-stmikplk** [osi-stmikplk/siakad#24]
@bangHaji Urutan tahun ajaran spy DESC atau yg tampil hanya tahun ajaran aktif aja di halaman admin spp/kelas

**Comment by osi-stmikplk** [comment]
Mohon untuk tahun ajaran Aktif ini yang mana, apa 5 tahun kebelakang?

**Comment by banghajidotcom** [comment]
- sebaiknya default list yg ditampilkan adalah tahun ajaran aktif terbaru, misal 20152
- untuk dropdown tahun ajaran ditampilkan secara DESC dan "mungkin" sebaiknya ditampilkan hanya 2 semester terakhir (misal sekarang 20152, maka yg tampil hanya 20152 dan 20151; jika sekarang 20161, maka yg tampil hanya 20161 dan 20152)
- sedangkan kolom pencarian tetap bisa digunakan untuk mencari semua tahun ajaran

**Comment by osi-stmikplk** [comment]
Oke ngerti saya, ini karena untuk proses status SPP jadi memang tidak begitu dibutuhkan bila loading sampai semua tahun ajaran. Jadi memang pas-nya adalah loading pada tahun ajaran seperti disampaikan.

**Comment by banghajidotcom** [comment]
bener friend, karena validasi SPP berlaku hanya utk semester aktif sajah, adapun utk halaman kelas&dosen itu bisa 2 semester utk misalnya perbaikan nilai semester sebelumnya, dst

haduh, nge-fetch lagi saya :+1:  :sunglasses:

**Comment by banghajidotcom** [comment]
pada halaman status spp, masih muncul mahasiswa yang sudah dikeluarkan dan atau mahasiswa yg nonaktif cukup lama; kalo yg lulus sudah tidak tampil :+1: 

nah ini perlu disepakati apakah tetap ditampilkan atau bagaimana?

**Comment by osi-stmikplk** [comment]
Benar ini masih muncul ... Apakah yang ditampilkan hanya aktif saja? 

Kalau melihat dari kegunaannya untuk spp berarti yang aktif saja ...

**Comment by banghajidotcom** [comment]
Yg tampil hanya mhs dgn status N, C dan A saja, sisanya tidak ditampilkan lagi.

btw, dari bagian akma harus memeriksa satu per satu mhs yg statusnya nonaktif itu apakah masih ada kemungkinan aktif lagi atau dipastikan "hilang" ditelan bumi yg katanya "datar"?
karena dari data yg ada byk mhs yg sdh keluar atau pindah tetapi statusnya masih (N)onaktif...

**Comment by osi-stmikplk** [comment]
> Yg tampil hanya mhs dgn status N, C dan A saja, sisanya tidak ditampilkan lagi.

Ini bisa dibuat dengan cepat dengan menambahkan query tambahan pada bagian render bootstrap-table.

> btw, dari bagian akma harus memeriksa satu per satu mhs yg statusnya nonaktif itu apakah masih ada kemungkinan aktif lagi atau dipastikan "hilang" ditelan bumi yg katanya "datar"?

Kalau kemungkinan aktif lagi itu bagian dari administrasi, tapi untuk melakukan perubahan status kemahasiswa AKMA bisa ke master > mahasiswa dan ada pada bagian setting status mahasiswa.  Jadi tidak hilang begitu saja.

**Comment by osi-stmikplk** [comment]
Untuk filter yang ditampilkan pada bagian ini apakah yang C (CUTI) ditampilkan juga? 

Bisa dilihat untuk filter ini sudah dilakukan 

https://github.com/osi-stmikplk/siakad/blob/master/app/Factories/StatusSPPFactory.php#L44

Namun di sini yang cuti saja yang belum dimasukkan.

**Comment by banghajidotcom** [comment]
Mhs (C)uti pasti boleh aktif lagi :ghost:

**Comment by osi-stmikplk** [comment]
Dalam pandangan saya saat mahasiswa memiliki status Cuti maka untuk melakukan pengisian KRS, status yang dilakukan harus dengan mendatangi pihak AKMA untuk melakukan reset status tidak lagi Cuti. Kalau tidak nantinya variable terhadap status mahasiswa bisa tidak tersinkron dengan baik.

Bagaimana dengan pendapat tersebut @banghaji ? Ini supaya aspek administrasi bisa lebih tercatat dengan baik.

**Comment by banghajidotcom** [comment]
nah kalo itu bagus juga friend @osi-stmikplk :sunglasses:  :+1:

**Comment by osi-stmikplk** [comment]
Sip kalau begitu deal ... kasus ditutup :sunglasses:
