### ISSUE TITLE
Rendering dan filter tampilan halaman Dosen & Kelas

### ISSUE THREAD

**Issue by banghajidotcom** [osi-stmikplk/siakad#25]
Pada halaman ini ketika diakses data akan di-load semuanya mulai dari tahun ajaran paling awal sampai dengan yg terakhir (data sementara sebanyak +- 5620 record).

Hal ini tidak praktis dan cenderung meningkatkan waktu loading, sebaiknya yg ditampilkan pertama kali hanya list dosen&kelas aktif semester berjalan saja.

Khusus untuk filter dropdown tetap disediakan pilihan tahun ajaran tetapi dibatasi hanya 2 semester terakhir (misalnya utk koreksi/perbaikan data, dst), sedangkan tahun semester sebelum itu bisa diabaikan karena sudah melebihi 2 semester terakhir.

**Comment by osi-stmikplk** [comment]
Friend, untuk loading menggunakan bootstrap table memang tidak melakukan loading semua data karena pada setting proses paging dilakukan di server dan bukan di client. Untuk data yang di render hanyalah 10 records saja, sedangkan jumlah yang muncul hanya mengambil menggunakan perintah count seperti layaknya sistem paging secara tradisional.

Untuk dropdown bagaimana dengan kasus untuk melihat sejarah mata kuliah pada tahun ajaran lama?

**Comment by banghajidotcom** [comment]
> Friend, untuk loading menggunakan bootstrap table memang tidak melakukan loading semua data karena pada setting proses paging dilakukan di server dan bukan di client. Untuk data yang di render hanyalah 10 records saja, sedangkan jumlah yang muncul hanya mengambil menggunakan perintah count seperti layaknya sistem paging secara tradisional.

kalo gitu tampilannya yg langsung diload utk semester aktif friend, supaya ga pilih tahun ajaran

> Untuk dropdown bagaimana dengan kasus untuk melihat sejarah mata kuliah pada tahun ajaran lama?

data pilihan di dropdown disediakan 2 semester terakhir, tetapi pada kolom pencarian masih bisa menampilkan data tahun ajaran yg lama2

**Comment by osi-stmikplk** [comment]
Telah diselesaikan :sunglasses:
