### ISSUE TITLE
Matakuliah ganda pada Transkrip Akademik

### ISSUE THREAD

**Issue by banghajidotcom** [osi-stmikplk/siakad#29]
Hari sabtu kemaren (2016-08-06) setelah KeJar, ada pertanyaan (sekaligus masukan) dari mahasiswa bahwa matakuliah yang dia tempuh muncul 2 kali dengan nilai yang berbeda.

Perbedaan nilai karena pernah mengulang, hanya saja kesalahan dari mahasiswa adalah mengambil matakuliah yang sama tetapi dengan kode yang berbeda.

Nilai mahasiswa tersebut seperti gambar berikut:

![dobel_mtk_beda_kode](https://cloud.githubusercontent.com/assets/15196503/17466958/f4ce3250-5d42-11e6-9089-d88cada26dea.PNG)

Mungkin untuk filter matakuliah di halaman Transkrip Akademik tidak hanya berdasarkan kode tetapi juga di set berdasarkan nama matakuliah.

**Comment by osi-stmikplk** [comment]
Terjadi karena perubahan kurikulum, MK yang sama memiliki beban yang berbeda dengan kode yang berbeda. Khusus untuk ini harus ada solusi ...

**Comment by banghajidotcom** [comment]
baca mantra dulu supaya @abdidnugraha dan pak @qules hadir di sini... :sunglasses:

**Comment by osi-stmikplk** [comment]
Saya pikir satu solusinya adalah field baru khusus untuk kasus seperti ini. Satu buah field yang berisikan kode MK yang diulang.

**Comment by banghajidotcom** [comment]
> Saya pikir satu solusinya adalah field baru khusus untuk kasus seperti ini. Satu buah field yang berisikan kode MK yang diulang.

Bagaimana jika mahasiswa mengulang lebih dari satu kali :disappointed: 

Solusi paling mudah adalah (tapi menambah pekerjaan bagian AKMA; dan juga programmer :smile:  ) yaitu dengan menambah satu field khusus pada rincian_studi untuk status (0/1).

Maka untuk "Transkrip Akademik" tidak perlu query GROUP/HAVE dst, cukup tampilkan mtk yang statusnya "1" saja. Sedangkan KHS, cukup tampilkan berdasarkan TA saja.

**Comment by osi-stmikplk** [comment]
> Solusi paling mudah adalah (tapi menambah pekerjaan bagian AKMA; dan juga programmer :smile: ) yaitu dengan menambah satu field khusus pada rincian_studi untuk status (0/1).

Bisa dideskripsikan lebih lanjut untuk ini? Maksudnya kalau nilai 0 ini tidak ditampilkan dan kalau 1 ini ditampilkan begitu?

Bisa dijelaskan dengan sebuah studi kasus? Misalnya saat si Mahasiswa melakukan pengambilan MK?

**Comment by banghajidotcom** [comment]
Misal, saya ambil mtk Mobile di semester 4, dapat nilai D, kemudian mengulang pada semester 6 dapat nilai C, lalu mengulang lagi pada semester 8 malah dapat E. Setelah itu tobat ga mau ngulang lagi :smile: 

Maka nilai yang diambil dan ditampilkan tentu yang nilainya C. Masalahnya adalah saya salah pilih kode mtk walaupun nama mtk sama.

Nah pada kasus ini, KHS semester 4 harus tetap tampil nilai D pada mtk Mobile, demikian pulan pada KHS semester 6 dan 8.

Tetapi ada Transkrip Akademik, yang seharusnya tampil hanya yang nilainya tertinggi yaitu C.

Untuk menangani ini, mahasiswa harus melapor ke AKMA, kemudian AKMA mengubah status (ingat, statusnya bukan nilainya) dari nilai D dan E menjadi "0" dengan asumsi default value untuk status adalah "1" dan filter pada Transkrip Akademik adalah yang statusnya = "1"

Cape ngetiknya friend, mending aq bikin tutorial biar sekalian keliatan muka :laughing: 

Intinya sih, tambahn fungsi/tugas pada bagian AKMA, sekaligus tambah kerjaan programmer :sunglasses:

**Comment by osi-stmikplk** [comment]
Berarti ini khusus yang double dan **khusus untuk transkrip akademik**, bukan pada KHS semester dan tentunya tetap mempengaruhi IPS.

Jadi ada fasilitas pada AKMA yang khusus untuk kasus seperti ini bakal ada sebuah field aktiv atau tidak dengan nilai 1 atau 0.

Nama fasilitasnya adalah: AKMA > filter MK Double :sunglasses:

**Comment by banghajidotcom** [comment]
> Berarti ini khusus yang double dan khusus untuk transkrip akademik, bukan pada KHS semester dan tentunya tetap mempengaruhi IPS.

Yup bukan pada KHS, TIDAK mempengaruhi IPS (karena utk semester nilainya tetap sesuai yang diperoleh walaupun mengulang). Tetapi berpengaruh pada IPK di Transkrip Akademik (karena tidak akan ikut menghitung nilai yang statusnya "0")

**Comment by abdidnugraha** [comment]
Baru muncul udah solved.. :laughing: 

Lanjut pdpt dlu :runner: :runner:

**Comment by qulez** [comment]
hadir gan... :dancer:

**Comment by qulez** [comment]
jiah....udh solved.. :dancers:

**Comment by qulez** [comment]
apakah pada saat input KRS, Mata kuliah yang ditawarkan bisa langsung difilter berdasarkan Jurusan dan Tahun Angkatan pak yan? agar kasus di atas tidak terulang?

**Comment by qulez** [comment]
Oke za tu pak yan idenya...filter di akma untuk matakuliah transkrip nilai.

**Comment by osi-stmikplk** [comment]
@qulez untuk proses inputan memang terfilter.

Namun ini masalahnya terhadap data yang telah ada sekarang.

Sorry agak lama ini untuk fixing nya :melon:

**Comment by banghajidotcom** [comment]
Sama, saya juga lama nunggunya :sunglasses:  :laughing: :laughing: :laughing: 

Sabar friend, semakin banyak commit dan pull-request, semakin besar itungannya :smile:

**Comment by qulez** [comment]
Banghaji : ane lom pernah commit dan pull ney... T_T

**Comment by osi-stmikplk** [comment]
@qulez @banghaji yang belum pernah commit bakal di potong :laughing: :laughing: 

Paling lambat besok neh, banyak yang mesti dirubah ternyata.

**Comment by osi-stmikplk** [comment]
Mohon di check @banghaji dan confirm kalau sudah fix!

**Comment by osi-stmikplk** [comment]
Oke fix sudah ... Tak Close :sunglasses: :gun:
