### ISSUE TITLE
Mahasiswa Lulus masih bisa mengisi FRS

### ISSUE THREAD

**Issue by banghajidotcom** [osi-stmikplk/siakad#3]
login sebagai mhs dengan status lulus masih bisa mengisi FRS

**Comment by osi-stmikplk** [comment]
Perlu dibahas ini apa saja akses yang bisa diberikan kepada mahasiswa yang sudah lulus. 

Kalau untuk mahasiswa yang lulus memang fasilitas ini tidak usah ditampilkan.
