### ISSUE TITLE
Order By Karena Tipe Data Migrasi Untuk Semester

### ISSUE THREAD

**Issue by osi-stmikplk** [osi-stmikplk/siakad#32]
Dari migrasi pada table rencana_studi untuk field semester menggunakan tipe data varchar.

hal ini menyebabkan saat di sorting, misalkan ada semester:

1 2 3 4 5 6 7 ... 10 11 12

Setelah di sorting menjadi 

1 10 11 12 ... 2 3 4 

Semestinya

1 2 3 4 5 6 ..

Hal ini karena tipe data adalah varchar, mestinya diganti menjadi numeric ...

**Comment by banghajidotcom** [comment]
ga perlu migrasi, cukup ubah tipe data utk field semester (kan sudah ada field nya sekaligus isinya)

**Comment by osi-stmikplk** [comment]
sudah dirubah :tired_face: coba check di riwayat akademik, cari yang semester sudah > 9 semester (mahasiswa lama)

**Comment by osi-stmikplk** [comment]
Dapat masalahnya, perhatikan pada bagian source code ini 

https://github.com/osi-stmikplk/siakad/blob/dev/app/Factories/HasilStudyMahasiswaFactory.php#L92

Di sana terlihat bahwa yang di order semester yang ada di table rincian_studi, padahal saat ini kita sudah pindahkan ke rencana_studi. Jadi saat dirubah rincian_studi semester menjadi numeric (tiny int) baru hasilnya benar.
