### ISSUE TITLE
Fasilitas Input Absen

### ISSUE THREAD

**Issue by osi-stmikplk** [osi-stmikplk/siakad#34]
Bagian Akma dapat memasukkan absensi Mahasiswa pada Tahun Ajaran aktiv.

**Comment by banghajidotcom** [comment]
pada sistem yg lama, proses entry presensi ini dilakukan setiap akhir/awal bulan

**Comment by osi-stmikplk** [comment]
Diinputkan itu apa pertambahan jumlahnya?

**Comment by banghajidotcom** [comment]
yup, misal bulan I 4 => presensi = 4, bulan II 3 => presensi = 7, dst, input yg terakhir selalu ditambahkan ke presensi yg sudah pernah di entry sebelumnya

**Comment by osi-stmikplk** [comment]
fc9ff44b3f21a640060f903c1505b339cd00b2d3

Jangan lupa untuk melakukan migrate karena ada tambahan fields
