### ISSUE TITLE
Filter tahun ajaran di akun mahasiswa

### ISSUE THREAD

**Issue by banghajidotcom** [osi-stmikplk/siakad#4]
tahun ajaran sebaiknya (seharusnya) hanya tampil mulai tahun ajaran yang ditempuh mhs ybs friend :D

**Comment by osi-stmikplk** [comment]
ini sepertinya memang menjadi pertimbangkan, karena membutuhkan loading pada bagian tampilan di indeks pengisian ...

**Comment by osi-stmikplk** [comment]
56b6e3eebc6cf221651941bed67b25c29b73bed0 DONE!
