### ISSUE TITLE
Masalah Nilai Di Bagian Hasil Studi Eror

### ISSUE THREAD

**Issue by c1357201013** [osi-stmikplk/siakad#40]
Nilai saya yang semester 6 untuk matakuliah Pemrograman Framework, malah E untuk nilai nya, sedangkan di KHS yang sudah di cetak, nilai nya B, mohon bantuan nya, untuk melakukan pengecekan kembali, untuk Hasil Studi saya. Nim : C1357201013 / Nama : Miftah Hidayat

**Comment by osi-stmikplk** [comment]
Sedang di check untuk ini ...

**Comment by osi-stmikplk** [comment]
Sudah di check di data online nilai untuk Pemrograman Framework adalah memang E, hal ini dikarenakan belum tersinkron antara nilai yang di online dengan nilai baru yang di AKMA versi offline (SIM lama). Mohon ditunggu penanganannya ...

**Comment by c1357201013** [comment]
terima kasih, atas bantuan nya...

**Comment by c1357201013** [comment]
iya pak, nilai nya untuk yang versi online nya, malah E, yg di KHS yg sudah tercetak, nilai nya B, mohon bantuan nya ya pak..

**Comment by osi-stmikplk** [comment]
Untuk penyelesaiannnya kalau masih belum update langsung hubungi Pak Abdi di Akma atau dengan Pak Erfan di Lab. Nanti di close issue ini saat sudah update yah @c1357201013 :panda_face:

**Comment by c1357201013** [comment]
iya, nnti saya cek kembali, kalau masih blum ada perubahan saya tanya kembali ke Pak Abdi atau sama pak Erfan., trimakasih atas bantuan nya..

**Comment by banghajidotcom** [comment]
Sudah diselesaikan friend @osi-stmikplk cc @c1357201013 :sunglasses:

**Comment by osi-stmikplk** [comment]
Kalau begitu saya close ya, dan apabila ada masalah lagi open lagi ... Saya belum makan :panda_face:

**Comment by banghajidotcom** [comment]
makan dulu friend, habis tu kerja keras lagi :disappointed:  :laughing:
