### ISSUE TITLE
Tampilan peminat/pengambil mtk pada akun Admin/Akma

### ISSUE THREAD

**Issue by banghajidotcom** [osi-stmikplk/siakad#41]
kalau bisa ditambahkan kolom tampilan utk peminat/pengambil matakuliah (dosen dan kelas) di akun Admin/Akma :smile:

**Comment by osi-stmikplk** [comment]
Maksudnya gimana Friend? Bisa dijelaskan lebih lengkap apa yang disediakan?

**Comment by banghajidotcom** [comment]
close friend, oke seperti itu... :+1:
