### ISSUE TITLE
jumlah sks

### ISSUE THREAD

**Issue by kdwiligwina** [osi-stmikplk/siakad#42]
misi gan mau tanya, di khs punya saya di tertulis maksimal untuk semester 5 adalah 24 sks. Tapi waktu nyetak frs tertera di bilang 23 sks. Itu kenapa ya gan

**Comment by osi-stmikplk** [comment]
Jumlah SKS yang kamu ambil adalah 24 SKS, sedangkan jatah untuk semester ini berdasarkan hasil sebelumnya adalah 23 SKS, sehingga system memberikan warning.

Sila check di sini dan bandingkan dengan IPS semester sebelumnya.

https://github.com/osi-stmikplk/siakad/blob/dev/app/Factories/IsiFRSFactory.php#L298

**Comment by banghajidotcom** [comment]
@kdwiligwina  silahkan dikurangi jumlah sks (mtk yg akan diambil) karena akan diminta merubah oleh dosen PA. Kasus Anda sebenarnya maksimal SKS hanya 23 tetapi diambil 24.

**Comment by kdwiligwina** [comment]
Ips saya semester 5   3,75 tapi kenapa di siakad 3,46. Utk matakuliah metodologi penelitian sya belum pernah ambil, tapi kenapa di nilai saya ada.

**Comment by banghajidotcom** [comment]
Masukkan screenshot atau foto KHS Anda yg dari Akma, biasanya itu terjadi karena waktu mnegisi KRS sebelumnya pernah mengambil mtk tsb kemudian dihapus.

Kirim filenya di kolom komentar ini supaya bisa kami tindak lanjuti mtk tsb.

**Comment by kdwiligwina** [comment]
![p_20160822_070735](https://cloud.githubusercontent.com/assets/20085643/17840672/71a6461a-6837-11e6-872c-e05680563ae9.jpg)
![a](https://cloud.githubusercontent.com/assets/20085643/17840685/b875276e-6837-11e6-9c34-8f7559d560de.png)

**Comment by osi-stmikplk** [comment]
Bagaimana ini apakah sudah Fix?

**Comment by banghajidotcom** [comment]
sudah fix, boleh di-close friend... :+1:

**Comment by banghajidotcom** [comment]
@kdwiligwina , sudah diperbaiki, mohon untuk di close issue ini :sunglasses:

**Comment by kdwiligwina** [comment]
terima kasih banyak pak :)
