### ISSUE TITLE
Absensi Mahasiswa Ada Mahasiswa Tidak Muncul

### ISSUE THREAD

**Issue by osi-stmikplk** [osi-stmikplk/siakad#52]
Pada pencetakan absensi mahasiswa, ada mahasiswa yang muncul di input absensi, tapi tidak muncul pada fasilitas pencetakan absensi.

**Comment by osi-stmikplk** [comment]
Hal ini terjadi karena status KRS masih draft, pada input absen ditampilkan semua walaupun masih draft, sehingga dibuat lebih konsisten!

**Comment by banghajidotcom** [comment]
seharusnya semua data FRS yang statusnya "DRAFT" itu dihapus dari tabel/database apabila sudah melewati masa penyusunan/persetujuan.
