### ISSUE TITLE
Validasi pengisian FRS

### ISSUE THREAD

**Issue by banghajidotcom** [osi-stmikplk/siakad#6]
Hasil masukan dari mahasiswa setelah testing pagi tadi:
- SPP belum dicek
- Limit SKS maksimal berdasarkan IPS belum ada
- Masih bisa ngisi lebih dari 25 SKS
- Baru sampai DRAFT, belum PERSETUJUAN

**Comment by osi-stmikplk** [comment]
Untuk persetujuan Draft masih dalam penyelesaian, hal yang lain mestinya diselesaikan pada push berikutnya ...

**Comment by osi-stmikplk** [comment]
@banghaji untuk limit SKS apa harus tidak boleh mengambil lebih? 

Apa ini lebih baik ditampilkan sebagai pesan saja? Karena yang bisa nanti menentukan adalah si Dosen Wali ...

**Comment by banghajidotcom** [comment]
maksimal SKS secara umum adalah 25, tapi harus disesuaikan dengan maksimal IPS masing-masing mhs

**Comment by osi-stmikplk** [comment]
Ada sebahagian kasus SKS diambil lebih besar daripada jatah dan ini disetujui oleh Dosen Wali. Bagaimana dengan kasus ini? 

Apa tidak sebaiknya ini dijadikan sebagai warning pada tampilan dan cetakan FRS waktu draft saja?

**Comment by osi-stmikplk** [comment]
dc8f4d8757143d6ed49abd2b064c923697a04739 telah menambahkan untuk proses persetujuan FRS

**Comment by osi-stmikplk** [comment]
Proses validasi terakhir untuk maksimal SKS bisa diambil berdasarkan IPS adalah dilakukan oleh Dosen Wali, sedangkan sistem akan menampilkan berupa catatan pada FRS. Telah diselesaikan pada d2bc66906af72dd8cf0cbca8516ceb9df7e3129b
