### ISSUE TITLE
Filter Mahasiswa Di Halaman Admin Kadang Error

### ISSUE THREAD

**Issue by heriproj** [osi-stmikplk/siakad#9]
Untuk filter data "Search" di halaman admin terkadang ada error. Case Yang di coba
- [ ] Saat input nama mahasiswa pada input search yang di inginkan "Heri Setiawan" tetapi kadang input   search jadi "HeriSetiawan" spasinya tiba" hilang. ^_^ hehehehehehe....
- [ ] Searchnya mood"an kata bang Haji. Kadang kalo search pakai mahasiswa Lulus bisa kadang ndak bisa. Case yang dilakukan Kalo input nama mahasiswa lulus HERI SETIAWAN dan DEDY YUSMAN. Nama HERI SETIAWAN muncul tetapi nama DEDY YUSMAN tidak muncul. 
- [ ] Tapi kalo pakai filter spesifik filter LULUS baru muncul...

Sementara itu dulu ^_^

**Comment by yfktn** [comment]
> Saat input nama mahasiswa pada input search yang di inginkan "Heri Setiawan" tetapi kadang input   search jadi "HeriSetiawan" spasinya tiba" hilang. ^_^ hehehehehehe....

Hal ini karena setting pada Bootstrap Table, jadi ada setting yang membuat spasi tidak dapat dimasukkan. Hal ini akan dijadikan sebagai inputan untuk penambahan fasilitas ...

Bisa dilihat di link ini pada bagian **trimOnSearch**

http://bootstrap-table.wenzhixin.net.cn/documentation/

Ada yang mau pull request? (^-^)

**Comment by yfktn** [comment]
> Searchnya mood"an kata bang Haji. Kadang kalo search pakai mahasiswa Lulus bisa kadang ndak bisa. Case yang dilakukan Kalo input nama mahasiswa lulus HERI SETIAWAN dan DEDY YUSMAN. Nama HERI SETIAWAN muncul tetapi nama DEDY YUSMAN tidak muncul.

Coba check di status mahasiswa, untuk HERI SETIAWAN status mahasiswa adalah N :D sedangkan yang DEDY YUSMAN belum ku check.

Untuk tampilan data mahasiswa supaya tidak terlalu banyak yang tampil maka default tampil adalah yang status mahasiswa masih kuliah ( https://github.com/osi-stmikplk/siakad/blob/dev/app/Factories/MahasiswaFactory.php#L46 )
